// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_month_ from "./routes/[month].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $PeopleEditor from "./islands/PeopleEditor.tsx";
import * as $Roster from "./islands/Roster.tsx";
import * as $RosterEntry from "./islands/RosterEntry.tsx";
import * as $RosterPage from "./islands/RosterPage.tsx";
import * as $SettingsCheckbox from "./islands/SettingsCheckbox.tsx";
import * as $StaffEditor from "./islands/StaffEditor.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[month].tsx": $_month_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/PeopleEditor.tsx": $PeopleEditor,
    "./islands/Roster.tsx": $Roster,
    "./islands/RosterEntry.tsx": $RosterEntry,
    "./islands/RosterPage.tsx": $RosterPage,
    "./islands/SettingsCheckbox.tsx": $SettingsCheckbox,
    "./islands/StaffEditor.tsx": $StaffEditor,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
